"""Build the Core Economy NML entry point and optionally compile the GRF.

NML is compiled from a single entry-point file. Keep the implementation
modular in source control, then deterministically assemble the entry point.
The same script can compile a local GRF so GitHub Actions is verification,
not a required build service.
"""
from pathlib import Path
import argparse
import shutil
import subprocess

ROOT = Path(__file__).resolve().parents[1]
NEWGRF = ROOT / "games" / "openttd" / "newgrf"
OUTPUT = NEWGRF / "core_economy.nml"
DEFAULT_GRF = ROOT / "build" / "core_economy.grf"
LANG = NEWGRF / "lang"

HEADER = """// AUTO-GENERATED ENTRY POINT — DO NOT EDIT DIRECTLY.
// Generated by tools/build_newgrf.py from the modular NML sources.
// Core Economy v0.4.x OpenTTD NewGRF

grf {
    grfid: \"CE\\04\\01\";
    name: string(STR_GRF_NAME);
    desc: string(STR_GRF_DESC);
    version: 1;
    min_compatible_version: 1;
}

// Canonical cargo translation table. This is the stable label mapping used
// by the Core Economy adapter. FEAT_CARGOS item IDs are independent OpenTTD
// cargo slots: built-in cargos are reused, custom cargos occupy slots 12+.
cargotable {
    GRAI, LVST, WOOD, FISH, COAL, IORE, STON, CLAY, OIL_, GAS_, CORE, SAND,
    BAUX, TIO_, GORE, SORE, REOR, COKE, STEL, COPP, GLAS, CERA, ALUM, TITN,
    GOLD, SILV, REMT, LIME, CEMT, FOOD, LUMB, PETR, MACH, CHEM, MNFG, ELEC,
    ADVG, HARD, INDE, CNST, AGRI, TECH, FUEL, PASS, PERS, MAIL
}
"""

FRAGMENTS = (
    "cargoes.nml",
    "graphics.nml",
    "production.nml",
    "industries.nml",
)


def prepare_fragment(filename: str, text: str) -> str:
    """Return NML-safe source for the assembled entry point."""
    if filename == "cargoes.nml" and text.startswith("// Core Economy canonical cargo definitions."):
        marker = "// Primary extraction and resource cargos."
        if marker in text and "#define CARGO_DEFAULT_PROPERTIES" in text:
            text = text[text.index(marker):]
    return text


def assemble() -> Path:
    """Assemble the deterministic NML entry point from source fragments."""
    parts = [HEADER.rstrip(), ""]
    for filename in FRAGMENTS:
        path = NEWGRF / filename
        if not path.is_file():
            raise SystemExit(f"missing NML source fragment: {path}")
        text = path.read_text(encoding="utf-8").rstrip()
        text = prepare_fragment(filename, text)
        parts.extend([f"// --- {filename} ---", text, ""])

    OUTPUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"NML ENTRY POINT GENERATED: {OUTPUT.relative_to(ROOT)}")
    print("fragments: " + ", ".join(FRAGMENTS))
    return OUTPUT


def compile_grf(output: Path) -> Path:
    """Compile the assembled NML entry point with the local nmlc executable."""
    nmlc = shutil.which("nmlc")
    if nmlc is None:
        raise SystemExit(
            "nmlc was not found on PATH. Install the NML compiler locally, "
            "then rerun: python tools/build_newgrf.py --compile"
        )
    output.parent.mkdir(parents=True, exist_ok=True)
    command = [
        nmlc,
        "-o",
        str(output),
        f"--lang={LANG}",
        str(OUTPUT),
    ]
    print("COMPILE:", " ".join(command))
    subprocess.run(command, cwd=ROOT, check=True)
    print(f"GRF BUILT: {output.relative_to(ROOT)}")
    return output


def main() -> int:
    parser = argparse.ArgumentParser(description="Build Core Economy OpenTTD NewGRF")
    parser.add_argument(
        "--compile",
        action="store_true",
        help="assemble and compile a local GRF with nmlc",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_GRF,
        help="local GRF output path (default: build/core_economy.grf)",
    )
    args = parser.parse_args()

    assemble()
    if args.compile:
        compile_grf(args.output if args.output.is_absolute() else ROOT / args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
