"""Assemble the modular Core Economy NML sources into the nmlc entry point.

NML is compiled from a single entry-point file. Keep the implementation
modular in source control, then deterministically assemble the entry point
before compilation.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NEWGRF = ROOT / "games" / "openttd" / "newgrf"
OUTPUT = NEWGRF / "core_economy.nml"

HEADER = """// AUTO-GENERATED ENTRY POINT — DO NOT EDIT DIRECTLY.
// Generated by tools/build_newgrf.py from the modular NML sources.
// Core Economy v0.4.x OpenTTD NewGRF

grf {
    grfid: \"CE\\04\\01\";
    name: string(STR_GRF_NAME);
    desc: string(STR_GRF_DESC);
    version: 1;
    min_compatible_version: 1;
}

// Canonical cargo translation table. Order is the stable adapter slot order.
cargotable {
    GRAI, LVST, WOOD, FISH, COAL, IORE, STON, CLAY, OIL_, GAS_, CORE, SAND,
    BAUX, TIO_, GORE, SORE, REOR, COKE, STEL, COPP, GLAS, CERA, ALUM, TITN,
    GOLD, SILV, REMT, LIME, CEMT, FOOD, LUMB, PETR, MACH, CHEM, MNFG, ELEC,
    ADVG, HARD, INDE, CNST, AGRI, TECH, FUEL, PASS, PERS, MAIL
}
"""

FRAGMENTS = (
    "cargoes.nml",
    "graphics.nml",
    "production.nml",
    "industries.nml",
)


def main() -> int:
    parts = [HEADER.rstrip(), ""]
    for filename in FRAGMENTS:
        path = NEWGRF / filename
        if not path.is_file():
            raise SystemExit(f"missing NML source fragment: {path}")
        text = path.read_text(encoding="utf-8").rstrip()
        parts.extend([f"// --- {filename} ---", text, ""])

    OUTPUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"NML ENTRY POINT GENERATED: {OUTPUT.relative_to(ROOT)}")
    print("fragments: " + ", ".join(FRAGMENTS))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
